import Image from "next/image";
import { ArrowUpRight } from "lucide-react";
import { company } from "@/data/company";
import { productSets } from "@/data/media";

const systems=[
  ["A.01","Instrument care","OPA · PA · GA · Enzymatic systems",productSets.taslak3[0]],
  ["A.02","Surface control","Rapid surface and environmental disinfection",productSets.taslak3[2]],
  ["A.03","Patient care","Barrier and antibacterial care systems",productSets.taslak3[4]],
];

export function HomeSections(){return <>
  <section className="relative min-h-[92svh] overflow-hidden bg-[#080b0f] text-white"><Image src="/images/factory/van-fabrika.jpg" alt="KAF Grup üretim tesisi" fill priority sizes="100vw" className="object-cover opacity-55"/><div className="absolute inset-0 bg-[linear-gradient(90deg,rgba(8,11,15,.96)_0%,rgba(8,11,15,.82)_42%,rgba(8,11,15,.25)_78%,rgba(8,11,15,.5)_100%)]"/><div className="absolute inset-0 opacity-15" style={{backgroundImage:"linear-gradient(rgba(255,255,255,.18) 1px,transparent 1px),linear-gradient(90deg,rgba(255,255,255,.18) 1px,transparent 1px)",backgroundSize:"64px 64px"}}/><div className="relative mx-auto flex min-h-[92svh] max-w-[1360px] flex-col justify-between px-5 py-12 sm:px-8 lg:px-10 lg:py-16"><div className="flex justify-between text-[10px] tracking-[0.22em] text-white/45 uppercase"><span>KAF Industrial Systems</span><span>IST · TR</span></div><div className="max-w-4xl py-16"><p className="text-xs font-semibold tracking-[0.2em] text-[#f0a33e] uppercase">Medical manufacturing infrastructure</p><h1 className="mt-6 text-5xl leading-[0.92] font-semibold tracking-[-0.055em] sm:text-7xl lg:text-[6.8rem]">Built for<br/>controlled production.</h1><p className="mt-7 max-w-xl text-lg leading-relaxed text-white/60">GMP üretim, Class 1000 / 10.000 / 100.000 temiz oda altyapısı ve global tedarik için ölçeklenebilir medikal üretim.</p><a href="#systems" className="mt-9 inline-flex items-center gap-2 border border-[#f0a33e] bg-[#f0a33e] px-5 py-3 text-sm font-semibold text-[#080b0f]">Explore systems <ArrowUpRight className="size-4"/></a></div><div className="grid grid-cols-2 gap-px bg-white/15 lg:grid-cols-4">{[["15.000 m²","capacity"],["50+","markets"],["GMP","standard"],["25+ years","experience"]].map(([v,l])=><div key={l} className="bg-[#080b0f]/75 p-5 backdrop-blur"><p className="text-2xl font-semibold">{v}</p><p className="mt-1 text-[10px] tracking-[0.18em] text-white/40 uppercase">{l}</p></div>)}</div></div></section>

  <section id="systems" className="bg-[#0d1117] text-white"><div className="mx-auto max-w-[1360px] px-5 py-20 sm:px-8 lg:px-10 lg:py-28"><div className="grid gap-8 lg:grid-cols-12"><div className="lg:col-span-4"><p className="text-[10px] tracking-[0.22em] text-[#f0a33e] uppercase">System portfolio</p><h2 className="mt-4 text-4xl font-semibold tracking-tight">Products grouped by clinical workflow.</h2></div><div className="lg:col-span-8"><div className="border-t border-white/15">{systems.map(([code,title,desc,img])=><article key={code} className="grid gap-6 border-b border-white/15 py-8 sm:grid-cols-[80px_1fr_180px] sm:items-center"><span className="text-xs font-mono text-[#f0a33e]">{code}</span><div><h3 className="text-2xl font-semibold">{title}</h3><p className="mt-2 text-sm text-white/45">{desc}</p></div><div className="relative h-32 bg-[#141922]"><Image src={img} alt="" fill sizes="180px" className="object-contain p-4"/></div></article>)}</div></div></div></div></section>

  <section className="bg-[#141922] text-white"><div className="mx-auto grid max-w-[1360px] gap-10 px-5 py-20 sm:px-8 lg:grid-cols-12 lg:px-10 lg:py-24"><div className="lg:col-span-7"><div className="relative aspect-[16/10] overflow-hidden border border-white/10"><Image src="/images/factory/van-fabrika.jpg" alt="Van üretim tesisi" fill sizes="(max-width:1024px) 100vw, 58vw" className="object-cover"/><div className="absolute bottom-0 left-0 bg-[#080b0f]/85 px-4 py-3 text-xs tracking-[0.15em] text-white/60 uppercase">YYÜ Teknokent · Van</div></div></div><div className="lg:col-span-5"><p className="text-[10px] tracking-[0.22em] text-[#f0a33e] uppercase">Manufacturing data</p><h2 className="mt-4 text-4xl font-semibold tracking-tight">Control is part of the product.</h2><p className="mt-5 text-base leading-relaxed text-white/50">Üretim alanları, temiz oda sınıfları ve kalite süreçleri; pazarlama iddiası değil, operasyonun temel bileşeni.</p><dl className="mt-8 divide-y divide-white/12 border-y border-white/12">{[["Clean room classes","1.000 · 10.000 · 100.000"],["Quality system","GMP"],["Facilities","İstanbul · Van"],["Export footprint","50+ countries"]].map(([k,v])=><div key={k} className="flex justify-between gap-6 py-4 text-sm"><dt className="text-white/35">{k}</dt><dd className="text-right font-medium">{v}</dd></div>)}</dl></div></div></section>

  <section className="bg-[#0d1117] text-white"><div className="mx-auto max-w-[1360px] px-5 py-20 sm:px-8 lg:px-10 lg:py-24"><div className="grid gap-12 lg:grid-cols-12"><div className="lg:col-span-4"><p className="text-[10px] tracking-[0.22em] text-[#f0a33e] uppercase">OEM production</p><h2 className="mt-4 text-4xl font-semibold tracking-tight">From specification to shipment.</h2></div><div className="grid gap-px bg-white/12 sm:grid-cols-3 lg:col-span-8">{[["01","Define","Ürün, pazar ve teknik gereksinim"],["02","Validate","Numune, kalite ve ambalaj onayı"],["03","Produce","Seri üretim, test ve sevkiyat"]].map(([n,t,d])=><div key={n} className="bg-[#0d1117] p-6"><p className="font-mono text-xs text-[#f0a33e]">{n}</p><h3 className="mt-12 text-xl font-semibold">{t}</h3><p className="mt-3 text-sm leading-relaxed text-white/45">{d}</p></div>)}</div></div></div></section>

  <section className="border-t border-white/10 bg-[#080b0f] text-white"><div className="mx-auto flex max-w-[1360px] flex-col gap-6 px-5 py-16 sm:px-8 lg:flex-row lg:items-center lg:justify-between lg:px-10"><div><p className="text-[10px] tracking-[0.22em] text-white/35 uppercase">Business development</p><h2 className="mt-3 text-3xl font-semibold">OEM, distribution or institutional supply.</h2></div><a href={`mailto:${company.contact.email}`} className="inline-flex items-center gap-2 text-sm font-semibold text-[#f0a33e]">Start a conversation <ArrowUpRight className="size-4"/></a></div></section>
</>}
