import Image from "next/image";
import { ArrowUpRight } from "lucide-react";
import { company } from "@/data/company";
import { productSets } from "@/data/media";

const stories = [
  { no:"01", brand:"ONESEPT", title:"Sterilizasyonun görünmeyen standardı", text:"Tıbbi cihaz ve endoskop süreçleri için yüksek düzey dezenfeksiyon çözümleri.", image:productSets.taslak2[0] },
  { no:"02", brand:"ONE GEL", title:"Temasın başladığı yerde güven", text:"Ultrason, EKG ve girişimsel uygulamalar için geliştirilen medikal jel sistemleri.", image:productSets.taslak2[1] },
  { no:"03", brand:"WANCARE", title:"Bakımı daha pratik hale getiren ürünler", text:"Yatan hasta bakımı için antibakteriyel ve bariyer odaklı ürün ailesi.", image:productSets.taslak2[2] },
];

export function HomeSections(){return <>
  <section className="bg-[#f1eee7] text-[#151515]"><div className="mx-auto grid min-h-[86svh] max-w-[1440px] grid-cols-1 lg:grid-cols-12">
    <div className="flex flex-col justify-between border-r border-black/10 px-5 py-10 sm:px-8 lg:col-span-5 lg:px-12 lg:py-14"><div><p className="text-xs tracking-[0.24em] text-[#d97800] uppercase">KAF Journal · Issue 01</p><h1 className="mt-8 font-[family-name:var(--font-fraunces)] text-6xl leading-[0.9] tracking-[-0.045em] sm:text-7xl lg:text-[6rem]">Products<br/><em className="font-normal text-black/45">with purpose.</em></h1><p className="mt-8 max-w-sm text-base leading-relaxed text-black/55">Ürünleri listelemek yerine; kullanım alanlarını, üretim yaklaşımını ve markaların arkasındaki fikri anlatan editoryal bir ürün dünyası.</p></div><div className="mt-12 flex items-center justify-between border-t border-black/15 pt-5 text-xs tracking-[0.16em] text-black/45 uppercase"><span>Medical manufacturing</span><span>Türkiye · 2026</span></div></div>
    <div className="relative min-h-[560px] overflow-hidden bg-[#e7e1d7] lg:col-span-7"><div className="absolute left-[6%] top-[10%] h-[72%] w-[42%] rotate-[-4deg]"><Image src={productSets.taslak2[0]} alt="" fill priority className="object-contain"/></div><div className="absolute right-[7%] top-[3%] h-[52%] w-[38%] rotate-[4deg]"><Image src={productSets.taslak2[1]} alt="" fill priority className="object-contain"/></div><div className="absolute bottom-[-2%] right-[18%] h-[46%] w-[42%] rotate-[-2deg]"><Image src={productSets.taslak2[2]} alt="" fill className="object-contain"/></div><p className="absolute bottom-6 left-6 max-w-[15rem] font-[family-name:var(--font-fraunces)] text-2xl leading-tight">Three product stories.<br/>One manufacturing culture.</p></div>
  </div></section>

  <section className="bg-white text-black"><div className="mx-auto max-w-[1100px] px-5 py-20 sm:px-8 lg:py-28"><p className="text-xs tracking-[0.22em] text-[#d97800] uppercase">Editor’s note</p><div className="mt-6 grid gap-8 lg:grid-cols-12"><h2 className="font-[family-name:var(--font-fraunces)] text-4xl leading-tight sm:text-5xl lg:col-span-7">Bir medikal üreticinin web sitesi yalnızca teknik bilgi vermek zorunda değil.</h2><p className="text-lg leading-relaxed text-black/55 lg:col-span-5">Ürünlerin arkasındaki üretim kültürünü, kalite yaklaşımını ve kullanım bağlamını da anlatabilir. Bu tasarım KAF Grup’u klasik katalog görünümünden çıkarıp modern bir ürün yayıncısına dönüştürüyor.</p></div></div></section>

  {stories.map((s,i)=><section key={s.no} className={i===1?"bg-[#151515] text-white":"bg-[#f1eee7] text-black"}><div className={`mx-auto grid max-w-[1440px] items-center lg:grid-cols-12 ${i%2?"":""}`}><div className={`relative min-h-[520px] lg:col-span-7 ${i%2?"lg:order-2":""}`}><Image src={s.image} alt={s.title} fill sizes="(max-width:1024px) 100vw, 58vw" className="object-contain p-10 sm:p-16 lg:p-20"/></div><div className={`px-5 py-14 sm:px-8 lg:col-span-5 lg:px-12 ${i%2?"lg:order-1":""}`}><p className={`text-xs tracking-[0.2em] uppercase ${i===1?"text-[#f0a33e]":"text-[#d97800]"}`}>{s.no} · {s.brand}</p><h2 className="mt-6 font-[family-name:var(--font-fraunces)] text-4xl leading-[1.05] sm:text-5xl">{s.title}</h2><p className={`mt-6 max-w-md text-base leading-relaxed ${i===1?"text-white/55":"text-black/55"}`}>{s.text}</p><a href="#contact" className="mt-8 inline-flex items-center gap-2 text-sm font-semibold">Ürün ailesini keşfet <ArrowUpRight className="size-4"/></a></div></div></section>)}

  <section className="bg-[#d97800] text-black"><div className="mx-auto max-w-[1440px] px-5 py-16 sm:px-8 lg:px-12 lg:py-20"><div className="grid gap-8 lg:grid-cols-12"><div className="lg:col-span-5"><p className="text-xs tracking-[0.2em] uppercase">Private label</p><h2 className="mt-4 font-[family-name:var(--font-fraunces)] text-4xl leading-tight sm:text-5xl">Fikriniz, bizim üretim altyapımız.</h2></div><div className="lg:col-span-7"><p className="max-w-xl text-lg leading-relaxed text-black/70">Formülasyon, numune, ambalaj ve üretim sürecini markanıza özel olarak birlikte geliştiriyoruz.</p><div className="mt-8 grid gap-px bg-black/25 sm:grid-cols-3">{["Brief & formülasyon","Numune & onay","Üretim & teslimat"].map((x,i)=><div key={x} className="bg-[#d97800] p-5"><span className="text-xs">0{i+1}</span><p className="mt-8 font-semibold">{x}</p></div>)}</div></div></div></div></section>

  <section id="contact" className="bg-[#151515] text-white"><div className="mx-auto flex max-w-[1440px] flex-col gap-6 px-5 py-16 sm:px-8 lg:flex-row lg:items-end lg:justify-between lg:px-12"><div><p className="text-xs tracking-[0.2em] text-white/40 uppercase">Next chapter</p><h2 className="mt-4 font-[family-name:var(--font-fraunces)] text-4xl sm:text-5xl">Let’s make the next product story together.</h2></div><a href={`mailto:${company.contact.email}`} className="text-sm font-semibold text-[#f0a33e]">{company.contact.email} ↗</a></div></section>
</>}
